language: generic
sudo: required
services:
  - docker

before-install:
  - docker build -t 16101996/docker-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true 16101996/docker-frontend npm run test
