#base 
FROM node:16-alpine

#directory of use
WORKDIR '/app'

#copy package.json
COPY ./package.json ./

#add dependency
RUN npm install


#copy rest
COPY . . 
#we can also use COPY ./ ./

#run the server command
CMD ["npm","run","start"]